language: ruby
rvm:
  - 2.1.0
install:
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts
  - sudo apt-get install texlive texlive-latex-extra
  - gem update --system # maybe fixes timeouts!?
  - gem install squib
script:
  - pdflatex rules.tex
  - ruby deck.rb
  - cp _output/start.pdf .
  - cp _output/middle.pdf .
  - cp _output/end.pdf .
  - zip RunOn.zip start.pdf middle.pdf end.pdf rules.pdf
addons:
  artifacts:
    paths:
    - RunOn.zip
